# Generated by Django 6.0.6 on 2026-09-17 22:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OfflineGameResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_key', models.CharField(max_length=64, unique=True)),
                ('quiz_id', models.IntegerField(blank=True, null=True)),
                ('quiz_title', models.CharField(blank=True, default='', max_length=255)),
                ('quiz_type', models.CharField(blank=True, default='', max_length=50)),
                ('time_per_question', models.IntegerField(default=15)),
                ('score', models.IntegerField(default=0)),
                ('correct_count', models.IntegerField(default=0)),
                ('answered_count', models.IntegerField(default=0)),
                ('total_questions', models.IntegerField(default=0)),
                ('completed_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offline_game_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-completed_at'],
            },
        ),
    ]
