# Generated by Django 6.0.6 on 2026-10-05 22:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
        ('users', '0017_remove_course_study_group_course_chat_group_id'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameRoom',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_code', models.CharField(max_length=16, unique=True)),
                ('quiz_id', models.IntegerField(blank=True, null=True)),
                ('topic', models.CharField(blank=True, default='', max_length=255)),
                ('mode', models.CharField(blank=True, default='classic', max_length=20)),
                ('team_mode', models.BooleanField(default=False)),
                ('question_count', models.IntegerField(default=0)),
                ('time_per_question', models.IntegerField(default=15)),
                ('player_count', models.IntegerField(default=0)),
                ('host_name', models.CharField(blank=True, default='', max_length=255)),
                ('status', models.CharField(choices=[('waiting', 'Waiting'), ('active', 'In progress'), ('finished', 'Finished')], default='waiting', max_length=20)),
                ('final_payload', models.JSONField(blank=True, null=True)),
                ('previous_round', models.JSONField(blank=True, null=True)),
                ('previous_round_finished_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='game_rooms', to='users.course')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hosted_game_rooms', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['course', '-created_at'], name='game_gamero_course__6d284b_idx'), models.Index(fields=['owner', '-created_at'], name='game_gamero_owner_i_c5afef_idx')],
            },
        ),
    ]
