# Generated by Django 6.0.6 on 2026-09-25 00:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0006_quiz_available_until_quizattempt'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quizattempt',
            options={'ordering': ['-started_at']},
        ),
        migrations.AlterUniqueTogether(
            name='quizattempt',
            unique_together=set(),
        ),
    ]
