# Generated by Django 6.0.6 on 2026-09-25 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0007_alter_quizattempt_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatsession',
            options={'ordering': ['-pinned', '-updated_at']},
        ),
        migrations.AddField(
            model_name='chatsession',
            name='pinned',
            field=models.BooleanField(default=False),
        ),
    ]
