# Generated by Django 6.0.6 on 2026-09-27 06:27

from django.conf import settings
from django.db import migrations, models


def _unpin_extras(apps, schema_editor):
    """Keep only the most recently updated pin per user.

    The previous API let a client set `pinned` on any number of sessions, so
    live data may already violate the new single-pin constraint and the
    AddConstraint below would abort the deploy. Unpin everything except the
    newest pin for each user.
    """
    ChatSession = apps.get_model('ai_assistant', 'ChatSession')
    seen = set()
    # Model Meta ordering is -pinned, -updated_at, so the first row per user
    # is the one to keep.
    for session in ChatSession.objects.filter(pinned=True).order_by('-updated_at', '-id'):
        if session.user_id in seen:
            ChatSession.objects.filter(id=session.id).update(pinned=False)
        else:
            seen.add(session.user_id)


class Migration(migrations.Migration):

    dependencies = [
        ('ai_assistant', '0008_alter_chatsession_options_chatsession_pinned'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='file_mime',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='file_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='chatmessage',
            name='file_size',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.RunPython(_unpin_extras, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='chatsession',
            constraint=models.UniqueConstraint(condition=models.Q(('pinned', True)), fields=('user',), name='uniq_pinned_session_per_user'),
        ),
    ]
