# Generated by Django 6.0.6 on 2026-09-20 13:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('quiz', 'Quiz'), ('lesson', 'Lesson'), ('game', 'Live Game')], default='quiz', max_length=20)),
                ('title', models.CharField(max_length=255)),
                ('ref_id', models.IntegerField(blank=True, null=True)),
                ('note', models.TextField(blank=True, default='')),
                ('due_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='users.course')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
