# Generated by Django 6.0.6 on 2026-09-21 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_ensure_bootstrap_superadmin'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
