# Generated by Django 6.0.6 on 2026-09-21 23:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_coursescore'),
    ]

    operations = [
        migrations.AddField(
            model_name='badge',
            name='course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='badges', to='users.course'),
        ),
    ]
