# Generated by Django 6.0.6 on 2026-09-22 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_badge_course'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='activity',
            name='course_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='activity',
            name='kind',
            field=models.CharField(default='other', max_length=20),
        ),
        migrations.AddField(
            model_name='activity',
            name='payload',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='activity',
            name='xp_earned',
            field=models.IntegerField(default=0),
        ),
    ]
