# Generated by Django 6.0.6 on 2026-08-16 15:01

import users.models
from django.db import migrations


def backfill_superuser_roles(apps, schema_editor):
    """Superusers created via `createsuperuser` after migration 0007 kept
    role='student' (nothing derived role from is_superuser). Force superadmin."""
    User = apps.get_model('users', 'User')
    User.objects.filter(is_superuser=True).exclude(role='superadmin').update(role='superadmin')


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_backfill_user_roles'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', users.models.SageUserManager()),
            ],
        ),
        migrations.RunPython(backfill_superuser_roles, migrations.RunPython.noop),
    ]
