# Generated by Django 6.0.6 on 2026-08-18 01:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_course'),
        ('users', '0008_alter_user_managers'),
    ]

    operations = [
    ]
