# Generated by Django 6.0.6 on 2026-09-23 23:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_activity_options_activity_course_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classactivity',
            name='kind',
            field=models.CharField(choices=[('quiz', 'Quiz'), ('lesson', 'Lesson'), ('game', 'Live Game'), ('task', 'Task')], default='quiz', max_length=20),
        ),
        migrations.CreateModel(
            name='TaskSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('file_mime', models.CharField(default='application/octet-stream', max_length=120)),
                ('file_size', models.IntegerField(default=0)),
                ('file_data', models.BinaryField()),
                ('submitted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='users.classactivity')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_submissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['submitted_at'],
                'unique_together': {('activity', 'student')},
            },
        ),
    ]
