# Generated by Django 6.0.6 on 2026-09-25 00:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_classactivity_kind_tasksubmission'),
    ]

    operations = [
        migrations.AddField(
            model_name='classactivity',
            name='max_points',
            field=models.PositiveIntegerField(default=100),
        ),
        migrations.AddField(
            model_name='tasksubmission',
            name='feedback',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='tasksubmission',
            name='graded_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tasksubmission',
            name='graded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='graded_submissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tasksubmission',
            name='score',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
