# Generated by Django 6.0.6 on 2026-09-25 11:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_classactivity_max_points_tasksubmission_feedback_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClassActivityAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('file_mime', models.CharField(default='application/octet-stream', max_length=120)),
                ('file_size', models.IntegerField(default=0)),
                ('file_data', models.BinaryField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='users.classactivity')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
