# Generated by Django 6.0.6 on 2026-09-25 22:27

import django.db.models.deletion
from django.db import migrations, models


def copy_submission_files(apps, schema_editor):
    """Move each turn-in's single file into its own TaskSubmissionFile row."""
    TaskSubmission = apps.get_model('users', 'TaskSubmission')
    TaskSubmissionFile = apps.get_model('users', 'TaskSubmissionFile')

    for submission in TaskSubmission.objects.all().iterator():
        if not submission.file_name:
            continue
        TaskSubmissionFile.objects.create(
            submission_id=submission.id,
            file_name=submission.file_name,
            file_mime=submission.file_mime,
            file_size=submission.file_size,
            file_data=submission.file_data,
        )


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_classactivityattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='classactivity',
            name='allow_multiple_files',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='tasksubmission',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='classactivity',
            name='due_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='TaskSubmissionFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('file_mime', models.CharField(default='application/octet-stream', max_length=120)),
                ('file_size', models.IntegerField(default=0)),
                ('file_data', models.BinaryField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='users.tasksubmission')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.RunPython(copy_submission_files, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='tasksubmission',
            name='file_data',
        ),
        migrations.RemoveField(
            model_name='tasksubmission',
            name='file_mime',
        ),
        migrations.RemoveField(
            model_name='tasksubmission',
            name='file_name',
        ),
        migrations.RemoveField(
            model_name='tasksubmission',
            name='file_size',
        ),
    ]
