# Generated by Django 6.0.6 on 2026-09-27 06:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_task_multi_file_and_due_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendation',
            name='course',
            # SET_NULL, not CASCADE: a student who enrolled a while ago can
            # have recommendations pointing at a course that has since been
            # deleted, and wiping those rows would silently empty their feed.
            # The serializer already tolerates a null course by falling back to
            # activities.
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recommendations', to='users.course'),
        ),
    ]
