# Generated by Django 6.0.6 on 2026-10-01 23:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_recommendation_topic'),
    ]

    operations = [
        migrations.CreateModel(
            name='AIUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('points', models.PositiveIntegerField(default=0)),
                ('calls', models.PositiveIntegerField(default=0)),
                ('prompt_tokens', models.PositiveIntegerField(default=0)),
                ('completion_tokens', models.PositiveIntegerField(default=0)),
                ('prompt_chars', models.PositiveIntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ai_usage', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-day'],
                'constraints': [models.UniqueConstraint(fields=('user', 'day'), name='uniq_ai_usage_user_day')],
            },
        ),
    ]
