# Generated by Django 6.0.6 on 2026-10-04 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_announcement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='study_group',
        ),
        migrations.AddField(
            model_name='course',
            name='chat_group_id',
            field=models.CharField(blank=True, default='', max_length=128),
        ),
    ]
