"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 6.0.4.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from datetime import timedelta
from pathlib import Path
import os
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
# (This points to: Development/SAGE_Project/backend_api/core)
BASE_DIR = Path(__file__).resolve().parent.parent
FIREBASE_CREDENTIALS_PATH = os.path.join(BASE_DIR, 'core', 'serviceAccountKey.json')
FIREBASE_PROJECT_ID = os.environ.get('FIREBASE_PROJECT_ID', 'sage-a47b8') 
# --- S3 (chat file attachments) ---
# The bucket stays private; the API hands out short-lived presigned links to
# verified group members only. Leave the keys unset for local dev / tests
# (uploads only touch AWS at runtime, and tests mock the S3 client).
AWS_ACCESS_KEY_ID = os.environ.get('AWS_ACCESS_KEY_ID')
AWS_SECRET_ACCESS_KEY = os.environ.get('AWS_SECRET_ACCESS_KEY')
AWS_S3_BUCKET_NAME = os.environ.get('AWS_S3_BUCKET_NAME', 'sage-chat-attachments')
AWS_S3_REGION_NAME = os.environ.get('AWS_S3_REGION_NAME', 'us-east-1')
AWS_S3_ENDPOINT_URL = os.environ.get('AWS_S3_ENDPOINT_URL')
# Presigned attachment links are valid for 30 minutes.
ATTACHMENT_LINK_TTL_SECONDS = int(os.environ.get('ATTACHMENT_LINK_TTL_SECONDS', 1800)) 
# --- SAGE SECRETS CONFIGURATION ---
# Go up two more folders to reach SAGE_Project, then look for .env
ENV_FILE_PATH = BASE_DIR.parent.parent / '.env'

# Load the variables into the environment
load_dotenv(ENV_FILE_PATH)

# Now, safely pull your DeepSeek key into Django's settings
DEEPSEEK_API_KEY = os.environ.get('DEEPSEEK_API_KEY')
GROQ_API_KEY = os.environ.get('GROQ_API_KEY')
# Gemini handles image questions in AI chat (DeepSeek is text-only). Unset
# means the app tells the user photo questions are unavailable rather than
# failing silently.
GEMINI_API_KEY = os.environ.get('GEMINI_API_KEY')
GEMINI_MODEL_NAME = os.environ.get('GEMINI_MODEL_NAME', 'gemini-2.0-flash')

# Number of prior chat messages sent to the AI for conversation memory
CHAT_MEMORY_LIMIT = int(os.environ.get('CHAT_MEMORY_LIMIT', 20))

# (Optional but highly recommended: You can also secure your Django Secret Key while you're at it!)
# SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'your-default-insecure-key-here')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
# SECURITY WARNING: keep the secret key used in production secret!
# Pull the key from the .env file.
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY')

# Add a quick safety check so the server won't start if the key is missing
if not SECRET_KEY:
    raise ValueError("The DJANGO_SECRET_KEY environment variable is not set!")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'False').lower() == 'true'

ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'users',
    'rest_framework',
    'rest_framework_simplejwt',
    'ai_assistant',
    'game'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'core.cors.CORSMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'core.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# When DATABASE_URL is provided (e.g. AWS RDS Postgres on Render), use it as the
# primary database; otherwise keep SQLite so local dev works unchanged.
if os.environ.get('DATABASE_URL'):
    import dj_database_url
    DATABASES = {'default': dj_database_url.config(conn_max_age=600, ssl_require=True)}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Tell Django REST Framework to use JWTs for authentication
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'users.authentication.TokenVersionAuthentication',
    ),
}

SIMPLE_JWT = {
    # Make the access token last for 7 days instead of 5 minutes
    'ACCESS_TOKEN_LIFETIME': timedelta(days=7),
    
    # Make the refresh token last for 30 days
    'REFRESH_TOKEN_LIFETIME': timedelta(days=30),

    # Embed role / token_version in our JWTs
    'TOKEN_OBTAIN_SERIALIZER': 'users.authentication.SAGETokenObtainPairSerializer',

    # simplejwt refreshes with an unguarded `User.objects.get`, so a refresh
    # token whose user row is gone (a rebuilt database, a deleted account)
    # raises DoesNotExist and renders as a 500. The client treats a 5xx as
    # "the backend is waking up" and retries forever while holding the dead
    # token, so a 401 that logs the user out is the whole difference between
    # recoverable and stuck. See users.authentication.SAGETokenRefreshSerializer.
    'TOKEN_REFRESH_SERIALIZER': 'users.authentication.SAGETokenRefreshSerializer',

    # Pin the JWT signing key to the Django SECRET_KEY
    'SIGNING_KEY': SECRET_KEY,
}



# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'

STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

STORAGES = {
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}

# Chat attachments are sent as multipart bodies (default 2.5 MB cap would
# reject the allowed 10 MB chat files).
FILE_UPLOAD_MAX_MEMORY_SIZE = 12 * 1024 * 1024
DATA_UPLOAD_MAX_MEMORY_SIZE = 12 * 1024 * 1024

AUTH_USER_MODEL = 'users.User'

# --- Email (OTP delivery) ---
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
# Bound the SMTP connect so a dead egress path fails over to the next address
# (and surfaces 503) instead of hanging a gunicorn worker until it is killed.
# socket.create_connection tries smtp.gmail.com's addresses in order (IPv6
# first); with no timeout an unroutable family stalls forever and never falls
# through to IPv4, which is how a worker-abort SystemExit became a 500.
EMAIL_TIMEOUT = int(os.environ.get('EMAIL_TIMEOUT', '10'))
EMAIL_HOST_USER = os.environ.get('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.environ.get('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = os.environ.get('EMAIL_HOST_USER', 'noreply@sage.app')

# Email settings can be overridden for dev (e.g. EMAIL_BACKEND=console to print OTPs)
if os.environ.get('EMAIL_BACKEND'):
    EMAIL_BACKEND = os.environ['EMAIL_BACKEND']

# Email OTP second factor for Firebase email/password logins. On by default;
# set OTP_ENABLED=0 in .env for local dev when SMTP isn't available.
OTP_ENABLED = os.environ.get('OTP_ENABLED', '1').strip().lower() not in (
    '0', 'false', 'no', 'off',
)

# --- Cache ---
# DRF throttles count in Django's default cache, which is LocMemCache: one
# private dict per process. The Procfile runs `gunicorn --workers 2`, so every
# worker kept its own counter and the real limit was roughly double the
# configured rate, reset from scratch on every deploy. A database-backed cache
# is shared across workers and survives restarts, and it is the same Postgres
# (or SQLite locally) we already run on -- no new infrastructure.
#
# The table is created by `manage.py createcachetable`, which both Procfile
# commands run; see Procfile. Because no migration creates it, a database that
# never got that command turns every request into a 500 the moment a throttle
# writes its first counter, so core.cache.ResilientDatabaseCache degrades to an
# in-process cache instead of failing the request.
CACHES = {
    'default': {
        'BACKEND': 'core.cache.ResilientDatabaseCache',
        'LOCATION': 'django_cache',
        'OPTIONS': {
            # Throttle keys are one per (scope, user) pair, so the default 300
            # entries would evict live counters once a few hundred students are
            # active. MAX_ENTRIES is an LRU ceiling, not an upfront allocation.
            'MAX_ENTRIES': 10000,
            # DatabaseCache only purges expired rows when someone touches the
            # table. Without a cull frequency the table grows forever.
            'CULL_FREQUENCY': 300,
        },
    }
}

# --- DRF throttling ---
# ScopedRateThrottle is deliberately absent: it reads its scope off the view
# instance, which the two @api_view function-based views (generate_lesson,
# user_recommendations) cannot set without an undocumented .view_class
# assignment. The AI throttles in core.throttling subclass UserRateThrottle
# and hardcode `scope` instead, so they attach identically to function and
# class based views.
REST_FRAMEWORK['DEFAULT_THROTTLE_CLASSES'] = [
    'rest_framework.throttling.AnonRateThrottle',
    'rest_framework.throttling.UserRateThrottle',
]
REST_FRAMEWORK['DEFAULT_THROTTLE_RATES'] = {
    'anon': '100/day',
    'user': '1000/day',
    'otp': '20/hour',
    # --- AI burst throttles (core/throttling.py) ---
    # These are short-window safety rails. The daily budget that actually caps
    # spend is the weighted point quota in users/ai_usage.py, which is aware
    # that one lesson generation costs roughly ten chat turns.
    'ai_chat': os.environ.get('AI_THROTTLE_CHAT', '30/min'),
    'ai_quiz': os.environ.get('AI_THROTTLE_QUIZ', '10/hour'),
    'ai_lesson': os.environ.get('AI_THROTTLE_LESSON', '5/hour'),
    'ai_topic': os.environ.get('AI_THROTTLE_TOPIC', '10/hour'),
    'ai_recommend': os.environ.get('AI_THROTTLE_RECOMMEND', '5/hour'),
    'ai_game': os.environ.get('AI_THROTTLE_GAME', '10/hour'),
    # The TV display polls the room leaderboard every 2s for a whole session,
    # which is ~1800 requests/hour per screen and far above the anon budget.
    # Unauthenticated, so it needs its own bucket rather than the user rate;
    # see core.throttling.TvLeaderboardThrottle. Sized for several displays
    # sharing one classroom NAT -- raise or lower with TV_THROTTLE.
    'tv': os.environ.get('TV_THROTTLE', '18000/hour'),
}

# --- AI daily budget (users/ai_usage.py) ---
# Documented here rather than in the module so every AI limit is visible in one
# place; users/ai_usage.py is what actually reads them. Note the burst throttles
# above and the budget here are independent: raising AI_THROTTLE_LESSON to 50/h
# does not let a student generate 50 lessons, and lowering AI_BUDGET_STUDENT does
# not tighten the per-minute ceiling.
AI_BUDGET_DEFAULTS = {
    'AI_BUDGET_STUDENT': '50',
    'AI_BUDGET_EDUCATOR': '300',
    # 0 means unlimited -- there is no superadmin budget.
    'AI_BUDGET_SUPERADMIN': '0',
    # 0 means "no system-wide cap". Per-user budgets are the primary control.
    'AI_BUDGET_GLOBAL': '0',
    # Hours before an auto-generated recommendations request may call the
    # provider again. An explicit POST from the user ignores this.
    'AI_RECS_GET_COOLDOWN_HOURS': '6',
}